
theme: jekyll-theme-minimal
title: Javi's PHP Standards
layout: default
description: Bookmark this to keep an eye on my project updates!
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
